### ISSUE TITLE
Alternative to weird characters workaround

### ISSUE THREAD

**Issue by kreg** [hung-phan/babel-repl#5]
The weird characters workaround described in the README removes color from babel-node output. The following worked for me to preserve color but remove the unsupported ANSI move cursor and clear screen codes produced by babel-node:

```
(add-to-list 'comint-preoutput-filter-functions
             (lambda (output)
               (let ((y (replace-regexp-in-string "\033\\[1G" "" output)))
                 (let ((z (replace-regexp-in-string "\\(\033\\[0J> \033\\[3G\\)+" "> " y)))
                   z))))
```

**Comment by hung-phan** [comment]
👍  Thanks @kreg. Can you submit a PR for it? Will love to merge it?
